# Generated by Django 3.0.8 on 2020-07-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muscle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='code',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
